spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: msa
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: lb://first-service
          predicates:
            - Path=/first-service/**
            
        - id: second-service
          uri: lb://second-service
          predicates:
            - Path=/second-service/**
            
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login-service/**
          filters:
            - StripPrefix=1
            
        - id: my-react-app
          uri: http://localhost:5173
          predicates:
            - Path=/**
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true